version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: marketplace-db
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d   # <— всё .sql из migrations/ в initdb.d
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: marketplace-app
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${APP_PORT}:8080"

volumes:
  db_data:
